name: asyncio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3
  flutter_responsive_screen: ^1.0.0
  carousel_slider: ^1.3.0
  graphql_flutter: ^1.0.0
  url_launcher: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: TTCommons
      fonts:
        - asset: assets/fonts/TTCommons-Medium.ttf
        - asset: assets/fonts/TTCommons-Bold.ttf
          weight: 900
        - asset: assets/fonts/TTCommons-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
